# Generated by Django 5.0.4 on 2024-04-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='incomplete', max_length=20),
        ),
    ]
