# Generated by Django 5.0.4 on 2024-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_orderdatetime_alter_order_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(default='store_item_images/default.jpg', upload_to='store_item_images'),
        ),
    ]
