# Generated by Django 5.0.4 on 2024-04-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_storeitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='store_item_images'),
        ),
    ]
