# Generated by Django 5.0.4 on 2024-04-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_storeitem_image'),
        ('users', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='storeItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_item', to='store.storeitem'),
        ),
    ]
