# Generated by Django 5.0.4 on 2024-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_profile_alter_orderitem_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payMethod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
