# Generated by Django 5.0.4 on 2024-04-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_order_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
