# Generated by Django 5.0.4 on 2024-04-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='store_item_images/'),
        ),
    ]
