# Generated by Django 5.0.4 on 2024-04-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='Party City', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_region',
            field=models.CharField(blank=True, default='United States', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='Party State', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='streetAddress',
            field=models.CharField(blank=True, default='123 Easy Street', max_length=200),
        ),
    ]
