# Generated by Django 5.0.4 on 2024-04-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_address_default_address_address_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, default='000000000', max_length=9),
        ),
    ]
